# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Haonan Peng
email:
description: >- # this means to ignore newlines until "baseurl:"
  The personal website of Haonan Peng, a current Ph.D. Candidate in Electrical Engineering, with research focus on Surgical Robotics, Medical Device and and Machine learning.
twitter_username: None
github_username: HaonanPeng
minimal_mistakes_skin: default
search: true

# Build settings
markdown: kramdown
remote_theme: "mmistakes/minimal-mistakes@4.26.2"
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Haonan Peng"
  avatar : "/assets/images/photo_Haonan.png"
  bio    : "Surgical Robotics, Medical Devices, Machine Learning"
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://haonanpeng.github.io/"
    - label: "Curriculum Vitae"
      icon: "fas fa-file-pdf"  # PDF icon from Font Awesome
      url: "/assets/Curriculum Vitae - Haonan Peng (UW).pdf"
    - label: "Google Scholar"
      icon: "fas fa-graduation-cap"
      url: "https://scholar.google.com/citations?hl=en&user=K-Vjs90AAAAJ"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/HaonanPeng"

footer:
  links:
    - label: "Google Scholar"
      icon: "fas fa-graduation-cap"
      url: "https://scholar.google.com/citations?hl=en&user=K-Vjs90AAAAJ"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/HaonanPeng"

# defaults:
#   # _posts
#   - scope:
#       path: ""
#       type: posts
#     values:
#       layout: single
#       author_profile: true
#       read_time: true
#       comments: true
#       share: true
#       related: true
#   # _pages
#   - scope:
#       path: "_pages"
#       type: pages
#     values:
#       layout: single
#       author_profile: true

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: default
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  - scope:
      path: ""
      type: posts
    values:
      layout: default

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# Assets, this is to adjust the text wrap width
sass:
  style: compressed
assets:
  stylesheets:
    - "/assets/css/custom.css"

custom_css: |
  <style>
    .page__inner-wrap {
        max-width: 1200px !important;
        margin: 0 auto;
    }
    @media screen and (min-width: 1200px) {
        .page__inner-wrap {
            max-width: 1000px !important;
        }
    }
  </style>